name: CD

on:
    push:
        branches:
        - main
        paths:
        - 'infrastructure/**'
        - 'src/**'
        - 'scripts/**'
        - 'Cargo.toml'
        - './github/workflows/cd.yml'


jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Install Rust
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            override: true
        - name: Build Lambda functions
          run: python3 ./scripts/build.py
        - name: Plan Terraform
          run: terraform -chdir=infrastructure init
        - name: Plan Terraform
          run: terraform -chdir=infrastructure plan
        - name: Apply Terraform
          run: terraform -chdir=infrastructure apply