name: CI

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

env:
    RUSTFLAGS: -Dwarnings

jobs:
    rust-test:
        name: Test
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Install Rust
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            override: true
        - name: Run tests
          run: cargo test --all
    rust-clippy:
        name: Clippy
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Install Rust
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            override: true
        - name: Run clippy
          run: cargo clippy --all -- -D warnings
    rust-fmt:
        name: Fmt
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Install Rust
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            override: true
        - name: Run fmt
          run: cargo fmt --all -- --check
    terraform-init:
        name: Terraform Init
        env:
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_AWS_REGION: ${{ secrets.AWS_REGION }}
          TF_VAR_STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Install Terraform
          uses: hashicorp/setup-terraform@v1
        - name: Run terraform init
          run: terraform -chdir=infrastructure init
    terraform-validate:
        name: Terraform Validate
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Install Terraform
          uses: hashicorp/setup-terraform@v1
        - name: Run terraform validate
          run: terraform -chdir=infrastructure validate
    terraform-fmt:
        name: Terraform Fmt
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Install Terraform
          uses: hashicorp/setup-terraform@v1
        - name: Run terraform fmt
          run: terraform -chdir=infrastructure fmt -check